import { Project } from "./types";

export const fakeProjects: Project[] = [
  {
    id: "1",
    name: "Next.js Boilerplate",
    authorName: "John Doe",
    authorAvatar: "https://example.com/avatars/johndoe.jpg",
    description: "Get started with Next.js and React in seconds.",
    techStack: [
      "nextjs2",
      "reactjs",
      "tailwindcss",
      "mongodb",
      "js",
      "typescript",
    ],
    image:
      "https://tintin-nextjs-users-image.s3.ap-southeast-2.amazonaws.com/test41721270081869.png",
    projectTags: ["boilerplate", "starter", "next.js"],
    createdAt: new Date("2023-05-01"),
    lastUpdated: new Date("2023-06-01"),
  },
  {
    id: "2",
    name: "Image Gallery Starter",
    authorName: "Jane Smith",
    authorAvatar: "https://example.com/avatars/janesmith.jpg",
    description:
      "An image gallery built on Next.js and Cloudinary. Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    // Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    techStack: ["nextjs2", "reactjs", "tailwindcss", "mongodb"],
    image:
      "https://tintin-nextjs-users-image.s3.ap-southeast-2.amazonaws.com/dumplings.jpg",
    projectTags: ["gallery", "images", "cloudinary"],
    createdAt: new Date("2023-04-15"),
    lastUpdated: new Date("2023-05-10"),
  },
  {
    id: "3",
    name: "AI Chatbot",
    authorName: "Alice Johnson",
    authorAvatar: "https://example.com/avatars/alicejohnson.jpg",
    description: "A full-featured, hackable Next.js AI chatbot.",
    techStack: ["nextjs2", "reactjs", "tailwindcss", "mongodb"],
    image: "https://picsum.photos/300/200?random=1",
    projectTags: ["chatbot", "AI", "vercel"],
    createdAt: new Date("2023-07-01"),
    lastUpdated: new Date("2023-07-15"),
  },
  {
    id: "4",
    name: "E-Commerce Platform",
    authorName: "Michael Brown",
    authorAvatar: "https://example.com/avatars/michaelbrown.jpg",
    description: "A scalable and customizable e-commerce platform.",
    techStack: ["nextjs2", "reactjs", "tailwindcss", "mongodb"],
    image: "https://picsum.photos/300/200?random=2",
    projectTags: ["e-commerce", "platform", "graphql"],
    createdAt: new Date("2023-03-20"),
    lastUpdated: new Date("2023-04-05"),
  },
  {
    id: "5",
    name: "Personal Portfolio",
    authorName: "Emily White",
    authorAvatar: "https://example.com/avatars/emilywhite.jpg",
    description: "A sleek and modern personal portfolio built with Next.js.",
    techStack: ["nextjs2", "reactjs", "tailwindcss", "mongodb"],
    image: "https://picsum.photos/300/200?random=3",
    projectTags: ["portfolio", "personal", "next.js"],
    createdAt: new Date("2023-02-10"),
    lastUpdated: new Date("2023-03-01"),
  },
];


interface Tool {
  value: string
  label: string
}

export const frontEndTechnologies: Tool[] = [
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'reactjs', label: 'React' },
  { value: 'vue', label: 'Vue.js' },
  { value: 'angular', label: 'Angular' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'nuxtjs', label: 'Nuxt.js' },
  { value: 'redux', label: 'Redux' },
  { value: 'mobx', label: 'MobX' },
  { value: 'contextApi', label: 'Context API' },
  { value: 'bootstrap', label: 'Bootstrap' },
  { value: 'tailwindcss', label: 'Tailwind CSS' },
  { value: 'sass', label: 'Sass' },
  { value: 'reactRouter', label: 'React Router' },
  { value: 'vueRouter', label: 'Vue Router' },
  { value: 'angularRouter', label: 'Angular Router' },
  { value: 'formik', label: 'Formik' },
  { value: 'reactHookForm', label: 'React Hook Form' },
]

export const backEndTechnologies: Tool[] = [
  { value: 'nodejs', label: 'Node.js' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'go', label: 'Go (Golang)' },
  { value: 'rust', label: 'Rust' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'express', label: 'Express' },
  { value: 'django', label: 'Django' },
  { value: 'flask', label: 'Flask' },
  { value: 'springBoot', label: 'Spring Boot' },
  { value: 'aspnet', label: 'ASP.NET' },
  { value: 'rails', label: 'Ruby on Rails' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'sequelize', label: 'Sequelize' },
  { value: 'typeOrm', label: 'TypeORM' },
  { value: 'hibernate', label: 'Hibernate' },
  { value: 'entityFramework', label: 'Entity Framework' },
  { value: 'activeRecord', label: 'Active Record' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'sqlite', label: 'SQLite' },
  { value: 'sqlServer', label: 'Microsoft SQL Server' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'cassandra', label: 'Cassandra' },
  { value: 'couchdb', label: 'CouchDB' },
  { value: 'firebase', label: 'Firebase' },
]

export const devOpsTechnologies: Tool[] = [
  { value: 'git', label: 'Git' },
  { value: 'github', label: 'GitHub' },
  { value: 'gitlab', label: 'GitLab' },
  { value: 'bitbucket', label: 'Bitbucket' },
  { value: 'jenkins', label: 'Jenkins' },
  { value: 'travis', label: 'Travis CI' },
  { value: 'circleci', label: 'CircleCI' },
  { value: 'githubActions', label: 'GitHub Actions' },
  { value: 'gitlabCi', label: 'GitLab CI' },
  { value: 'docker', label: 'Docker' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'dockerCompose', label: 'Docker Compose' },
  { value: 'aws', label: 'AWS (Amazon Web Services)' },
  { value: 'gcp', label: 'Google Cloud Platform (GCP)' },
  { value: 'azure', label: 'Microsoft Azure' },
  { value: 'digitalOcean', label: 'DigitalOcean' },
  { value: 'terraform', label: 'Terraform' },
  { value: 'ansible', label: 'Ansible' },
  { value: 'cloudFormation', label: 'CloudFormation' },
]

export const testingTechnologies: Tool[] = [
  { value: 'jest', label: 'Jest' },
  { value: 'mocha', label: 'Mocha' },
  { value: 'junit', label: 'JUnit' },
  { value: 'nunit', label: 'NUnit' },
  { value: 'cypress', label: 'Cypress' },
  { value: 'selenium', label: 'Selenium' },
  { value: 'testcafe', label: 'TestCafe' },
  { value: 'puppeteer', label: 'Puppeteer' },
  { value: 'jmeter', label: 'JMeter' },
  { value: 'locust', label: 'Locust' },
]

export const monitoringTechnologies: Tool[] = [
  { value: 'prometheus', label: 'Prometheus' },
  { value: 'grafana', label: 'Grafana' },
  { value: 'newRelic', label: 'New Relic' },
  { value: 'datadog', label: 'Datadog' },
]

export const loggingTechnologies: Tool[] = [
  { value: 'elk', label: 'ELK Stack (Elasticsearch, Logstash, Kibana)' },
  { value: 'splunk', label: 'Splunk' },
  { value: 'loggly', label: 'Loggly' },
]

export const securityTechnologies: Tool[] = [
  { value: 'owaspZap', label: 'OWASP ZAP' },
  { value: 'burpSuite', label: 'Burp Suite' },
  { value: 'oauth', label: 'OAuth' },
  { value: 'jwt', label: 'JWT (JSON Web Tokens)' },
  { value: 'auth0', label: 'Auth0' },
  { value: 'firebaseAuth', label: 'Firebase Authentication' },
]

export const otherEssentialTools: Tool[] = [
  { value: 'npm', label: 'npm (Node Package Manager)' },
  { value: 'yarn', label: 'Yarn' },
  { value: 'pip', label: 'pip (Python)' },
  { value: 'maven', label: 'Maven' },
  { value: 'gradle', label: 'Gradle' },
  { value: 'webpack', label: 'Webpack' },
  { value: 'parcel', label: 'Parcel' },
  { value: 'vite', label: 'Vite' },
  { value: 'gulp', label: 'Gulp' },
  { value: 'postman', label: 'Postman' },
  { value: 'insomnia', label: 'Insomnia' },
  { value: 'vscode', label: 'Visual Studio Code' },
  { value: 'intellij', label: 'IntelliJ IDEA' },
  { value: 'pycharm', label: 'PyCharm' },
  { value: 'eclipse', label: 'Eclipse' },
  { value: 'sublimeText', label: 'Sublime Text' },
  { value: 'slack', label: 'Slack' },
  { value: 'microsoftTeams', label: 'Microsoft Teams' },
  { value: 'trello', label: 'Trello' },
  { value: 'jira', label: 'Jira' },
]

export const technologies: Tool[] = [
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'js', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'reactjs', label: 'React' },
  { value: 'vue', label: 'Vue.js' },
  { value: 'angular', label: 'Angular' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'nuxtjs', label: 'Nuxt.js' },
  { value: 'redux', label: 'Redux' },
  { value: 'mobx', label: 'MobX' },
  { value: 'contextApi', label: 'Context API' },
  { value: 'bootstrap', label: 'Bootstrap' },
  { value: 'tailwindcss', label: 'Tailwind CSS' },
  { value: 'sass', label: 'Sass' },
  { value: 'reactRouter', label: 'React Router' },
  { value: 'vueRouter', label: 'Vue Router' },
  { value: 'angularRouter', label: 'Angular Router' },
  { value: 'formik', label: 'Formik' },
  { value: 'reactHookForm', label: 'React Hook Form' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'go', label: 'Go (Golang)' },
  { value: 'rust', label: 'Rust' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'express', label: 'Express' },
  { value: 'django', label: 'Django' },
  { value: 'flask', label: 'Flask' },
  { value: 'springBoot', label: 'Spring Boot' },
  { value: 'aspnet', label: 'ASP.NET' },
  { value: 'rails', label: 'Ruby on Rails' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'sequelize', label: 'Sequelize' },
  { value: 'typeOrm', label: 'TypeORM' },
  { value: 'hibernate', label: 'Hibernate' },
  { value: 'entityFramework', label: 'Entity Framework' },
  { value: 'activeRecord', label: 'Active Record' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'sqlite', label: 'SQLite' },
  { value: 'sqlServer', label: 'Microsoft SQL Server' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'cassandra', label: 'Cassandra' },
  { value: 'couchdb', label: 'CouchDB' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'git', label: 'Git' },
  { value: 'github', label: 'GitHub' },
  { value: 'gitlab', label: 'GitLab' },
  { value: 'bitbucket', label: 'Bitbucket' },
  { value: 'jenkins', label: 'Jenkins' },
  { value: 'travis', label: 'Travis CI' },
  { value: 'circleci', label: 'CircleCI' },
  { value: 'githubActions', label: 'GitHub Actions' },
  { value: 'gitlabCi', label: 'GitLab CI' },
  { value: 'docker', label: 'Docker' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'dockerCompose', label: 'Docker Compose' },
  { value: 'aws', label: 'AWS (Amazon Web Services)' },
  { value: 'gcp', label: 'Google Cloud Platform (GCP)' },
  { value: 'azure', label: 'Microsoft Azure' },
  { value: 'digitalOcean', label: 'DigitalOcean' },
  { value: 'terraform', label: 'Terraform' },
  { value: 'ansible', label: 'Ansible' },
  { value: 'cloudFormation', label: 'CloudFormation' },
  { value: 'jest', label: 'Jest' },
  { value: 'mocha', label: 'Mocha' },
  { value: 'junit', label: 'JUnit' },
  { value: 'nunit', label: 'NUnit' },
  { value: 'cypress', label: 'Cypress' },
  { value: 'selenium', label: 'Selenium' },
  { value: 'testcafe', label: 'TestCafe' },
  { value: 'puppeteer', label: 'Puppeteer' },
  { value: 'jmeter', label: 'JMeter' },
  { value: 'locust', label: 'Locust' },
  { value: 'prometheus', label: 'Prometheus' },
  { value: 'grafana', label: 'Grafana' },
  { value: 'newRelic', label: 'New Relic' },
  { value: 'datadog', label: 'Datadog' },
  { value: 'elk', label: 'ELK Stack (Elasticsearch, Logstash, Kibana)' },
  { value: 'splunk', label: 'Splunk' },
  { value: 'loggly', label: 'Loggly' },
  { value: 'owaspZap', label: 'OWASP ZAP' },
  { value: 'burpSuite', label: 'Burp Suite' },
  { value: 'oauth', label: 'OAuth' },
  { value: 'jwt', label: 'JWT (JSON Web Tokens)' },
  { value: 'auth0', label: 'Auth0' },
  { value: 'firebaseAuth', label: 'Firebase Authentication' },
  { value: 'npm', label: 'npm (Node Package Manager)' },
  { value: 'yarn', label: 'Yarn' },
  { value: 'pip', label: 'pip (Python)' },
  { value: 'maven', label: 'Maven' },
  { value: 'gradle', label: 'Gradle' },
  { value: 'webpack', label: 'Webpack' },
  { value: 'parcel', label: 'Parcel' },
  { value: 'vite', label: 'Vite' },
  { value: 'gulp', label: 'Gulp' },
  { value: 'postman', label: 'Postman' },
  { value: 'insomnia', label: 'Insomnia' },
  { value: 'vscode', label: 'Visual Studio Code' },
  { value: 'intellij', label: 'IntelliJ IDEA' },
  { value: 'pycharm', label: 'PyCharm' },
  { value: 'eclipse', label: 'Eclipse' },
  { value: 'sublimeText', label: 'Sublime Text' },
  { value: 'slack', label: 'Slack' },
  { value: 'microsoftTeams', label: 'Microsoft Teams' },
  { value: 'trello', label: 'Trello' },
  { value: 'jira', label: 'Jira' },
]
